### ISSUE TITLE
Unknown id error when test scripts

### ISSUE THREAD

**Issue by cr04ch** [x1125/initd-light#1]
I get the following error: "Unknown id: /data/user/0/x1125io.initdlight/files/my_script". I think you have to use `su -c "sh [script]"` instead of `su -c sh [script]`.

**Comment by x1125** [comment]
Looking at [this](https://stackoverflow.com/questions/5969724/java-runtime-exec-fails-to-escape-characters-properly) and [this](https://stackoverflow.com/questions/23660096/runtime-exec-doesnt-run-commands-when-filename-has-spaces) stackoverflow example, the escaping should be correct.
Are you sure the "Unknown id" error isn't coming from one of your scripts?

**Comment by cr04ch** [comment]
Sorry, i'm not familiar with java but when i run the command `su -c sh my_script` in shell (over adb or in my linux box) i get the same error. I think in this form su interpret `sh` as command and `my_script` as username and not `sh my_script` as command.

When i run `su -c "sh my_script"` or `su -c 'sh my_script'` i get no error.

**Comment by x1125** [comment]
Could you tell me your su version? (`su --version`)

**Comment by cr04ch** [comment]
My version is 16 cm-su (from LineageOS Downloads Extras).

**Comment by cr04ch** [comment]
If I set execute permission to the script (`chmod 0755 my_script`), the `su -s sh -c my_script` works without error. But su uses /system/bin/sh as default shell, so `su -c my_script` also works, at least from the command line.

**Comment by x1125** [comment]
So it was a permission problem?

**Comment by cr04ch** [comment]
No, I just tried other ways to use the su from command line. If I use your syntax (but with quotes), I do not have to set the permission because my_script is interpreted as the first argument for sh. Without quotation marks it does not work at all because sh is interpreted as the command for -c switch of su and my_script is interpreted as the last argument of su.

**Comment by x1125** [comment]
Could you compile it youself and test it?
I made a new branch for this: [issue-1](https://github.com/x1125/initd-light/tree/issue-1)

If it works for you as expected, I would merge it into master and release it for public. :)

**Comment by cr04ch** [comment]
I tried it. Unfortunately, it did'nt work either. It was the same error message. So I deleted the "sh" from the code:
`int exitCode = pr.Run(new String[] { "su", "-c", fullFilePath });`
It works without error. Of course, only if the script has an execute permission. But this is not a problem for me.

**Comment by x1125** [comment]
Okey, this also works for me, so I merged this into master. :)
Can you verify it's working like that? Then I'd release the changes as a new version

**Comment by cr04ch** [comment]
Yes, that works for me at system boot. You just have to change this line in `MainActivity.java` too so that "Test scripts" button will work identically.

**Comment by teleshoes** [comment]
same issue for me. "su", "-c", "sh" + "fullFilePath"

is there an apk built with sh removed?

```
root@klte:/data # su -c sh /data/user/0/x1125io.initdlight/files/a.sh
Unknown id: /data/user/0/x1125io.initdlight/files/a.sh
root@klte:/data # su -c 'sh /data/user/0/x1125io.initdlight/files/a.sh'     
hello
```

**Comment by x1125** [comment]
Yeah sorry, I was busy. [Here](https://github.com/x1125/initd-light/blob/master/app/app-release.apk) is the current version as apk. I'll trigger the F-Droid update. :)

**Comment by teleshoes** [comment]
@x1125 OMG THANKS

this works perfectly ootb, unlike the 6 other crappy apps i tried.
i just use it to start a chroot, and then mount android partitions in the chroot, but you wouldnt believe the headache its been to get this simple task done at startup.

can i send a donation, please?

(off topic, but i checked your homepage for a donation link and saw your t430 edp adventure. did you ever get the auo panel installed? i installed the same panel in my T430s using  javi-jie's edp adapter, but i REALLY want it in my T430)

**Comment by x1125** [comment]
@teleshoes Wow that's nice to hear! Thank you :)

Also thanks for the donation, but I'm good :) If you really wan't to help, you could donate something to the F-Droid guys or some open source organisation in general.

(No, sadly nothing new, but I met a few guys at my new work which gave me some soldering advice, so I guess I'll try it the next month. :) Can I keep you up2date somehow? And great that you got one of those javi-jie's adapters! They seem to be such a rare thing :S )

**Comment by teleshoes** [comment]
thanks, i sent $20 to f-droid and an $20 to the FSF in addition to my dues.

and i would appreciate a shout if you ever do get t430 FHD working, but no pressure.

email: `elliot.wolk@gmail.com`

or post here, which i still check once a week or so like a sad puppy:
http://forum.thinkpads.com/viewtopic.php?f=45&t=122224&start=5000

**Comment by x1125** [comment]
Wow, that is great, thank you so much!

I'll save both your mail and the forum link :)
