### ISSUE TITLE
Incompatible with the popular Android devices

### ISSUE THREAD

**Issue by HiFromAjay** [x1125/initd-light#4]
The app supports min SDK 23, which is incompatible with some of the popular Android devices such as Galaxy J2, J1 Ace, Grand Prime, and Oppo A37f. These Android devices support min SDK 22. You can either decrease the SDK support of the current APK or provide another APK that supports min SDK < 23.

**Comment by x1125** [comment]
Hey there :)

Could you try to get a version running with the SDK version you require and have this as a PR in here?

**Comment by HiFromAjay** [comment]
Actually, I am developing a tool that can detect device compatibility issues without running apps on real devices. In the process of evaluating the tool, your app was flagged as incompatible with the aforementioned devices. I reported the issue in case you are interested in increasing the number of potential users. :)

**Comment by x1125** [comment]
Ah okey, nice work! :)
I'm actually quite busy right now, but if I get some more requests for this feature I'm looking forward to implement it.

**Comment by HiFromAjay** [comment]
Thank you for the response.
